List<Map<String, dynamic>> iCreamCategories = [
  {
    'category': 'Brand New',
    'details': [
      {
        'image': 'https://m.media-amazon.com/images/I/61fdx3j5BOL.jpg',
        'name': 'Choco Brownie Fudge',
        'brand': 'Kwality walls',
        'flavour': 'Brownie',
        'weight': 700,
        'price': 223,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/71PC37DtN-L._SL1500_.jpg',
        'name': 'Fruit N Nut Fantasy',
        'brand': 'Amul',
        'flavour': 'Cream fruit',
        'weight': 1000,
        'price': 195.5,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491390350/cadbury-5-star-3d-chocolate-45-g-product-images-o491390350-p491390350-0-202305301929.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury 5 Star 3D',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 45,
        'price': 28,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pvt. Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51hSIr6Y3FL.jpg',
        'name': 'Magnum Truffle',
        'brand': 'Kwality walls',
        'flavour': 'Truffle Chocolate',
        'weight': 62,
        'price': 99,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51896I1hszL.jpg',
        'name': 'Magnum Almond',
        'brand': 'Kwality walls',
        'flavour': 'Almond Chocolate',
        'weight': 62,
        'price': 90,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61tpf1U551L.jpg',
        'name': 'Black Forest',
        'brand': 'FlowerAura',
        'flavour': 'Black Forest',
        'weight': 500,
        'price': 499,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
    ]
  },
  {
    'category': 'Trending',
    'details': [
      {
        'image':
            'https://www.jiomart.com/images/product/original/491390350/cadbury-5-star-3d-chocolate-45-g-product-images-o491390350-p491390350-0-202305301929.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury 5 Star 3D',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 45,
        'price': 28,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pvt. Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51ktZrtGoXL._SL1000_.jpg',
        'name': 'Shameless Vanilla',
        'brand': 'Kwality walls',
        'flavour': 'Vanilla',
        'weight': 700,
        'price': 120,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61OsGBDhLXL.jpg',
        'name': 'Crunchy Butterscotch',
        'brand': 'Kwality walls',
        'flavour': 'Butterscotch',
        'weight': 700,
        'price': 144,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51hSIr6Y3FL.jpg',
        'name': 'Magnum Truffle',
        'brand': 'Kwality walls',
        'flavour': 'Truffle Chocolate',
        'weight': 62,
        'price': 99,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51896I1hszL.jpg',
        'name': 'Magnum Almond',
        'brand': 'Kwality walls',
        'flavour': 'Almond Chocolate',
        'weight': 62,
        'price': 90,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61tpf1U551L.jpg',
        'name': 'Black Forest',
        'brand': 'FlowerAura',
        'flavour': 'Black Forest',
        'weight': 500,
        'price': 499,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
    ]
  },
  {
    'category': 'All Brands',
    'details': [
      {
        'image': 'https://m.media-amazon.com/images/I/81+rY+FiGFL._SL1500_.jpg',
        'name': 'Amul Chocochips',
        'brand': 'Amul',
        'flavour': 'Chocolate',
        'weight': 1000,
        'price': 195.5,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/516DKArmejL.jpg',
        'name': 'Sundae Chocolate Magic',
        'brand': 'Amul',
        'flavour': 'Chocolate',
        'weight': 1000,
        'price': 182.75,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/71PC37DtN-L._SL1500_.jpg',
        'name': 'Fruit N Nut Fantasy',
        'brand': 'Amul',
        'flavour': 'Cream fruit',
        'weight': 1000,
        'price': 195.5,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51ktZrtGoXL._SL1000_.jpg',
        'name': 'Shameless Vanilla',
        'brand': 'Kwality walls',
        'flavour': 'Vanilla',
        'weight': 700,
        'price': 120,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61fdx3j5BOL.jpg',
        'name': 'Choco Brownie Fudge',
        'brand': 'Kwality walls',
        'flavour': 'Brownie',
        'weight': 700,
        'price': 223,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61OsGBDhLXL.jpg',
        'name': 'Crunchy Butterscotch',
        'brand': 'Kwality walls',
        'flavour': 'Butterscotch',
        'weight': 700,
        'price': 144,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51896I1hszL.jpg',
        'name': 'Magnum Almond',
        'brand': 'Kwality walls',
        'flavour': 'Almond Chocolate',
        'weight': 62,
        'price': 90,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51hSIr6Y3FL.jpg',
        'name': 'Magnum Truffle',
        'brand': 'Kwality walls',
        'flavour': 'Truffle Chocolate',
        'weight': 62,
        'price': 99,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image':
            'https://5.imimg.com/data5/SELLER/Default/2023/3/296046234/GS/TW/KW/4731140/royal-ice-cream-1000x1000.jpg',
        'name': 'Royal Mini Choco Bar',
        'brand': 'Royal',
        'flavour': 'Chocolate',
        'weight': 70,
        'price': 20,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Arun Dairy',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491642149/parle-poppins-100-g-product-images-o491642149-p590034271-0-202203151618.jpg?im=Resize=(1000,1000)',
        'name': 'Parle Poppins',
        'brand': 'Parle',
        'flavour': 'Fruits',
        'weight': 100,
        'price': 20,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Parle Products Pvt. Ltd',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491376009/kit-kat-dessert-delight-choco-pudding-wafer-chocolate-bar-50-g-product-images-o491376009-p590034263-0-202203170607.jpg?im=Resize=(1000,1000)',
        'name': 'KitKat Dessert Delight',
        'brand': 'KitKat',
        'flavour': 'Chocolate',
        'weight': 50,
        'price': 55,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Nestle India Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51Y9V0Nk+rL.jpg',
        'name': 'Choco Butterscotch',
        'brand': 'FlowerAura',
        'flavour': 'Butterscotch',
        'weight': 500,
        'price': 649,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/619Na9WZRQL.jpg',
        'name': 'Kitkat Oreo Wonder',
        'brand': 'FlowerAura',
        'flavour': 'Kitkat Chocolate',
        'weight': 500,
        'price': 629,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/31m9VkASAqL.jpg',
        'name': 'Chocolate Truffle',
        'brand': 'FlowerAura',
        'flavour': 'Truffle Chocolate',
        'weight': 500,
        'price': 799,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61tpf1U551L.jpg',
        'name': 'Black Forest',
        'brand': 'FlowerAura',
        'flavour': 'Black Forest',
        'weight': 500,
        'price': 499,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image':
            'http://4.imimg.com/data4/JI/YT/MY-15447013/paddle-pop-apple-grape-jelly-ice-cream-500x500.jpg',
        'name': 'Apple Grape Jelly',
        'brand': 'Paddle pop',
        'flavour': 'Apple grape',
        'weight': 60,
        'price': 10,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Neptune Distributors',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/490000239/cadbury-dairy-milk-crackle-chocolate-bar-36-g-product-images-o490000239-p490000239-0-202203141949.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury Dairy Milk',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 36,
        'price': 40,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pv. Ltd',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491390350/cadbury-5-star-3d-chocolate-45-g-product-images-o491390350-p491390350-0-202305301929.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury 5 Star 3D',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 45,
        'price': 28,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pvt. Ltd',
      },
    ],
  },
  {
    'category': 'Ice Creams',
    'details': [
      {
        'image': 'https://m.media-amazon.com/images/I/51ktZrtGoXL._SL1000_.jpg',
        'name': 'Shameless Vanilla',
        'brand': 'Kwality walls',
        'flavour': 'Vanilla',
        'weight': 700,
        'price': 120,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61fdx3j5BOL.jpg',
        'name': 'Choco Brownie Fudge',
        'brand': 'Kwality walls',
        'flavour': 'Brownie',
        'weight': 700,
        'price': 223,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61OsGBDhLXL.jpg',
        'name': 'Crunchy Butterscotch',
        'brand': 'Kwality walls',
        'flavour': 'Butterscotch',
        'weight': 700,
        'price': 144,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/81+rY+FiGFL._SL1500_.jpg',
        'name': 'Amul Chocochips',
        'brand': 'Amul',
        'flavour': 'Chocolate',
        'weight': 1000,
        'price': 195.5,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/516DKArmejL.jpg',
        'name': 'Sundae Chocolate Magic',
        'brand': 'Amul',
        'flavour': 'Chocolate',
        'weight': 1000,
        'price': 182.75,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/71PC37DtN-L._SL1500_.jpg',
        'name': 'Fruit N Nut Fantasy',
        'brand': 'Amul',
        'flavour': 'Cream fruit',
        'weight': 1000,
        'price': 195.5,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'GCMMF',
      }
    ]
  },
  {
    'category': 'Ice Cream Bars',
    'details': [
      {
        'image': 'https://m.media-amazon.com/images/I/51896I1hszL.jpg',
        'name': 'Magnum Almond',
        'brand': 'Kwality walls',
        'flavour': 'Almond Chocolate',
        'weight': 62,
        'price': 90,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51hSIr6Y3FL.jpg',
        'name': 'Magnum Truffle',
        'brand': 'Kwality walls',
        'flavour': 'Truffle Chocolate',
        'weight': 62,
        'price': 99,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Hindustan Unilever Ltd',
      },
      {
        'image':
            'https://5.imimg.com/data5/SELLER/Default/2023/3/296046234/GS/TW/KW/4731140/royal-ice-cream-1000x1000.jpg',
        'name': 'Royal Mini Choco Bar',
        'brand': 'Royal',
        'flavour': 'Chocolate',
        'weight': 70,
        'price': 20,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Arun Dairy',
      },
      {
        'image':
            'http://4.imimg.com/data4/JI/YT/MY-15447013/paddle-pop-apple-grape-jelly-ice-cream-500x500.jpg',
        'name': 'Apple Grape Jelly',
        'brand': 'Paddle pop',
        'flavour': 'Apple grape',
        'weight': 60,
        'price': 10,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Neptune Distributors',
      },
    ]
  },
  {
    'category': 'Candies',
    'details': [
      {
        'image':
            'https://www.jiomart.com/images/product/original/490000239/cadbury-dairy-milk-crackle-chocolate-bar-36-g-product-images-o490000239-p490000239-0-202203141949.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury Dairy Milk',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 36,
        'price': 40,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pv. Ltd',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491390350/cadbury-5-star-3d-chocolate-45-g-product-images-o491390350-p491390350-0-202305301929.jpg?im=Resize=(1000,1000)',
        'name': 'Cadbury 5 Star 3D',
        'brand': 'Cadbury',
        'flavour': 'Chocolate',
        'weight': 45,
        'price': 28,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Mondelez india food Pvt. Ltd',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491642149/parle-poppins-100-g-product-images-o491642149-p590034271-0-202203151618.jpg?im=Resize=(1000,1000)',
        'name': 'Parle Poppins',
        'brand': 'Parle',
        'flavour': 'Fruits',
        'weight': 100,
        'price': 20,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Parle Products Pvt. Ltd',
      },
      {
        'image':
            'https://www.jiomart.com/images/product/original/491376009/kit-kat-dessert-delight-choco-pudding-wafer-chocolate-bar-50-g-product-images-o491376009-p590034263-0-202203170607.jpg?im=Resize=(1000,1000)',
        'name': 'KitKat Dessert Delight',
        'brand': 'KitKat',
        'flavour': 'Chocolate',
        'weight': 50,
        'price': 55,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'Nestle India Ltd',
      }
    ]
  },
  {
    'category': 'Cakes',
    'details': [
      {
        'image': 'https://m.media-amazon.com/images/I/51Y9V0Nk+rL.jpg',
        'name': 'Choco Butterscotch',
        'brand': 'FlowerAura',
        'flavour': 'Butterscotch',
        'weight': 500,
        'price': 649,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/619Na9WZRQL.jpg',
        'name': 'Kitkat Oreo Wonder',
        'brand': 'FlowerAura',
        'flavour': 'Kitkat Chocolate',
        'weight': 500,
        'price': 629,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/31m9VkASAqL.jpg',
        'name': 'Chocolate Truffle',
        'brand': 'FlowerAura',
        'flavour': 'Truffle Chocolate',
        'weight': 500,
        'price': 799,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/61tpf1U551L.jpg',
        'name': 'Black Forest',
        'brand': 'FlowerAura',
        'flavour': 'Black Forest',
        'weight': 500,
        'price': 499,
        'count': 1,
        'country': 'India',
        'Manufacturer': 'FA Gifts Pvt Ltd',
      }
    ]
  }
];
